# _quarto.yml - Main configuration file
project:
  type: website
  output-dir: docs

website:
  title: "Programa de Campeon(a|e)s de rOpenSci"
  navbar:
    background: primary
    search: true
    left:
      - text: "Inicio"
        file: index.qmd
      - text: "Vision general"
        menu:
          - text: "Entrenamiento"
            file: program/training.qmd
          - text: "Proyectos"
            file: program/projects.qmd
          - text: "Divulgacion"
            file: program/outreach.qmd
          - text: "Finalización del programa"
            file: program/completion.qmd
      - text: "Campeon(a|e)s"
        menu:
          - text: "Resumen"
            file: champions/index.qmd
          - text: "Aplicar"
            file: champions/apply.qmd
      - text: "Mentor(a|e)s"
        menu:
          - text: "Resumen"
            file: mentors/index.qmd
          - text: "Aplicar"
            file: mentors/apply.qmd
      # - text: "For Instructors"
      #   menu:
      #     - text: "Overview"
      #       file: instructors/index.qmd
      #     - text: "Apply as Instructor"
      #       file: instructors/apply.qmd
      - text: "Recursos"
        menu:
          - text: "Materiales de capacitacion"
            file: resources/training.qmd
          - text: "Agenda"
            file: resources/agenda.qmd
          - text: "FAQ"
            file: resources/faq.qmd

  sidebar:
    - title: "Applications"
      contents:
        - section: "Join the Program"
          contents:
            - champions/apply.qmd
            - mentors/apply.qmd
            - instructors/apply.qmd
    - title: "Program Overview"
      contents:
        - program/training.qmd
        - program/projects.qmd
        - program/outreach.qmd
        - program/completion.qmd
    - title: "Resources"
      contents:
        - resources/training.qmd
        - resources/agenda.qmd
        - resources/faq.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



