# _quarto.yml - Main configuration file
project:
  type: website
  output-dir: docs

website:
  title: "rOpenSci"
  navbar:
    background: primary
    search: true
    left:
      - text: "Inicio"
        file: index.qmd
      - text: "Campeon(a|e)s"
        file: champions/index.qmd
      - text: "Mentor(a|e)s"
        file: mentors/index.qmd
      - text: "Recursos"
        file: resources/resources.qmd

  # sidebar:
  #   - title: "Aplicar"
  #     contents:
  #       - section: "Se parte del programa"
  #         contents:
  #           - champions/apply.qmd
  #           - mentors/apply.qmd
  #   - title: "El Programa"
  #     contents:
  #       - program/training.qmd
  #       - program/projects.qmd
  #       - program/outreach.qmd
  #       - program/completion.qmd
  #   - title: "Recursos"
  #     contents:
  #       - resources/training.qmd
  #       - resources/agenda.qmd
  #       - resources/faq.qmd

format:
  html:
#    css: css/ropensci.css
    css: css/extra.scss
    toc: false



